# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '36-FirebaseApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 36-FirebaseApp

pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
